-- 코드를 입력하세요
SELECT
    info.REST_ID AS REST_ID,
    info.REST_NAME AS REST_NAME,
    info.FOOD_TYPE AS FOOD_TYPE,
    info.FAVORITES AS FAVORITES,
    info.ADDRESS AS ADDRESS,
    ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO info
JOIN REST_REVIEW review ON review.REST_ID = info.REST_ID
WHERE info.ADDRESS LIKE '서울%'
GROUP BY info.REST_ID, info.REST_NAME, info.FOOD_TYPE, info.FAVORITES, info.ADDRESS
ORDER BY AVG(REVIEW_SCORE) DESC, FAVORITES DESC;