SELECT
    YEAR(sale.SALES_DATE) AS YEAR,
    MONTH(sale.SALES_DATE) AS MONTH,
    COUNT(DISTINCT sale.USER_ID) AS PURCHASED_USERS,
    ROUND(
        COUNT(DISTINCT sale.USER_ID) / (
            SELECT COUNT(*)
            FROM USER_INFO
            WHERE YEAR(JOINED) = 2021
        ),
        1
    ) AS PURCHASED_RATIO
FROM USER_INFO info
JOIN ONLINE_SALE sale
    ON info.USER_ID = sale.USER_ID
WHERE YEAR(info.JOINED) = 2021
GROUP BY YEAR(sale.SALES_DATE), MONTH(sale.SALES_DATE)
ORDER BY YEAR, MONTH;