SELECT
    YEAR(DIFFERENTIATION_DATE) as YEAR,
    maxi_year.maxi - SIZE_OF_COLONY as YEAR_DEV,
    ID
FROM ECOLI_DATA e, (
    SELECT
        YEAR(DIFFERENTIATION_DATE) as YEAR,
        MAX(SIZE_OF_COLONY) as maxi
    FROM ECOLI_DATA 
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) as maxi_year
WHERE YEAR(e.DIFFERENTIATION_DATE) = maxi_year.YEAR
ORDER BY YEAR, YEAR_DEV