SELECT
    f.id AS ID,
    i.FISH_NAME AS FISH_NAME,
    f.LENGTH AS LENGTH
FROM FISH_INFO f
JOIN (
    SELECT
        FISH_TYPE,
        MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) type_max
ON f.FISH_TYPE = type_max.FISH_TYPE AND f.LENGTH = type_max.LENGTH
JOIN FISH_NAME_INFO i
ON f.FISH_TYPE = i.FISH_TYPE
ORDER BY f.id